AWSTemplateFormatVersion: '2010-09-09'
Resources:
  lambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
          - Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}:*
          Version: '2012-10-17'
        PolicyName: Logging
    Type: AWS::IAM::Role
  main:
    Properties:
      CodeUri: s3://kter-serverless-repository/b0cebaf444b6dacf7437ef9c06c24867
      Handler: main.lambda_handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - lambdaRole
        - Arn
      Runtime: python3.6
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
